---
abstract: 'OS Package Management System'
author:
  - 'James F Wilkus <jfwilkus@cpan.org>'
build_requires:
  DateTime::Format::DateManip: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OS-Package
requires:
  Archive::Extract: '0'
  Cwd: '0'
  DateTime::Format::DateManip: '0'
  Digest::MD5: '0'
  Digest::SHA: '0'
  English: '0'
  Env: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '0'
  File::ShareDir: '0'
  File::Temp: '0'
  FileHandle: '0'
  Getopt::Long: '0'
  HTTP::Tiny: '0'
  Hash::AsObject: '0'
  IPC::Cmd: '0'
  Log::Dispatch: '0'
  Log::Log4perl: '0'
  Module::Load: '0'
  Moo: '0'
  POSIX: '0'
  Path::Tiny: '0'
  Pod::Usage: '0'
  Role::Tiny: '0'
  Template: '0'
  Time::Piece: '0'
  Try::Tiny: '0'
  Types::Standard: '0'
  YAML::Any: '0'
  base: '0'
  perl: v5.14.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jfwilkus/OS-Package/issues
  homepage: https://github.com/jfwilkus/OS-Package
  repository: https://github.com/jfwilkus/OS-Package.git
version: 0.2.5
