
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;

set_spell_cmd('aspell list');
add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
url
distfile
savefile
fakeroot
SHA
ospkg
os
workdir
init
github
metadata
James
Wilkus
jfwilkus
lib
OS
Package
Role
Build
Application
System
Plugin
Solaris
IPS
Maintainer
Factory
Config
Artifact
Log
Validate
Linux
deb
Clean
Extract
Download
SVR4
RPM
CLI
Init
Prune
